# IRC connection 
irc:
  host: 'irc.freenode.net'
  port: '6667'
  nick: boyscout
  channel: '#rubinius'

# HTTP Server

http:
  enabled: true
  host: 0.0.0.0
  port: '3469'
  # Enable post-receive stuff from Github
  github: true
  # Allow send with http
  send: true

# TCP Server

tcp:
  enabled: true
  host: 127.0.0.1
  port: '5678'
  size: 400
